### PR TITLE
Add script for getting a Travis Access Token from Github credentials

### PR DESCRIPTION
**Pull request by arichiardi**
The script is using boot, which must be installed on the machine in order to
work properly. Usage is simple:

```shell
./scripts/github-to-travis-token -u github-username -p github-password
```

### CODE REVIEW

**Comment by arichiardi** [comment]
Actually this could automate the `encrypt` step as well, why did I do this? Because I don't like `gem` and `ruby`, they clog my machine :smile:

**Comment by arichiardi** [comment]
I have also discovered [node-travis-encrypt](https://github.com/pwmckenna/node-travis-encrypt) for that step.

**Comment by darwin** [comment]
Thanks. LGTM. But I think your time would be better spent on other work. This script would likely need ongoing maintenance if github or travis decided to change the workflow. I would rather rely on official docs and tools than (potentially) providing an outdated docs/tool. But this is not a big issue - we are dealing with devs, they will be able to figure this out.

Also I don't like one minor thing on your script. Requesting passwords only on command-line as parameters is not a good practice. It should be possible to enter them interactively (with hidden typing). Command-line history might get stored in bash history or in other ways.

btw. If you don't want ruby polluting your env maybe you should consider using [rvm](https://rvm.io). Or run your ruby inside a docker container. Or writing a docker file which would automate whole process using official tools. That would be a better choice IMO.

**Comment by arichiardi** [comment]
@darwin you are definitely right about cmd line passwords. I was kind of playing around there and then this script popped up :smile: Probably you are right as well that my energy should be spend somewhere else :+1: 

Didn't know about `rvm`, I will definitely use that!

**Comment by darwin** [comment]
We can merge it. If it breaks I will ping you :-p

**Comment by arichiardi** [comment]
Btw `rvm` does not even install on my machine because it is failing the `gpg` check, thanks for merging! :dagger:

**Pull request merged**
